name: Send mail to myself

on:
  schedule:
  - cron: "10,30,50 * * * *"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # connection_url: ${{secrets.AUTOMATED_EMAIL_URL}}
          # Required mail server address if not connection_url:
          server_address: smtp.mail.yahoo.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.AUTOMATED_EMAIL_USER}}
          # Optional (recommended) mail server password:
          password: ${{secrets.AUTOMATED_EMAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: paul@stapor.de
          # Required sender full name (address can be skipped):
          from: Pauls Github Account
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
